name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

env:
  JAVA_OPTS: "-Xmx4G"
  JVM_OPTS: "-Xmx4G"
  SBT_OPTS: "-Xmx4G"

jobs:
  macos_build:
    name: MacOS
    strategy:
      fail-fast: true
      matrix:
        os: [macos-15, macos-15-intel]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: brew install ./sn-bindgen.rb && brew test sn-bindgen
      - run: brew install ./sniper.rb && brew test sniper
